### ISSUE TITLE
Improve UI and responsivness of player-card

### ISSUE THREAD

**Issue by Mr-Mime** [Mr-Mime/osrt#1]
The icons of the stat line are not vertically centered / aligned with the text:
![image](https://user-images.githubusercontent.com/37423773/227660848-7ae156d5-f031-415d-90af-3dd1f37ec43e.png)

Also for larger font, the stats might get lost to the right...
![image](https://user-images.githubusercontent.com/37423773/227660936-c6ad57f7-b9d8-4256-abc8-0b02756a2660.png)

**Comment by Yasir761** [comment]
Hey! Can you tell me the path of this particular issue?
Thank You

**Comment by Mr-Mime** [comment]
> Hey! Can you tell me the path of this particular issue? Thank You

It is the `player-card` component.
You find the relevant files under:
`src/app/components/player-card`

I guess the `.html` and `.scss` will need some adjustment.

Are you familiar on how to build the app with ionic?
I wanted to add a README.md the next days.

**Comment by Yasir761** [comment]
@Mr-Mime, Yes I'm familiar with ionic

**Comment by Yasir761** [comment]
Hey!, I guess this UI looks nicer.
![Screenshot 2023-03-25 224633](https://user-images.githubusercontent.com/74600745/227731982-72a9a31b-d8b7-4397-9c9c-00e4d9eb5c86.png)

**Comment by Mr-Mime** [comment]
@Yasir761 I agree, but I might would add a bit more spacing between the single stats.
If you made the changes feel free to create a PR :+1:
